management:
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST,PUT,OPTIONS,DELETE
        allowed-origins: '"*"'
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      livenessState:
        enabled: true
      readinessState:
        enabled: true
  info:
    env:
      enabled: true

selenium:
  enabled: true

spring:
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 250MB
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:5432/${DB_NAME:inferno-template}
    username: ${DB_USER:inferno-template}
    password: ${DB_PASS:inferno-template}
  jpa:
    hibernate:
      ddl-auto: update 
    open-in-view: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 6000
    database: 0
    connect-timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  jackson:
    default-property-inclusion: NON_NULL
server:
  forward-headers-strategy: native
  port: 8080
  servlet:
    contextPath: /inferno-template-rest
  shutdown: graceful
  tomcat:
    max-swallow-size: 250MB
    max-http-post-size: 250MB
    internal-proxies:
      protocol-header: "X-Forwarded-Proto"
      remote-ip-header: "X-FORWARDED-FOR"
  use-forward-headers: true

inferno-template:
  applicationName: "Infernotemplate"
  defaultAdminUsername: inferno-template_admin
  defaultAdminPassword: password
  encryptionKey: "${ENCRYPTION_KEY}"
  groqAPIKey: "${GROQ_API_KEY}"
  groqModel: "llama-3.1-8b-instant"
  descriptionGeneration: ${DESCRIPTION_GENERATION:true}
  recognitionServerHost: "${RECOGNITION_SERVER_HOST:localhost}"
  recognitionServerPort: "${RECOGNITION_SERVER_PORT:5000}"

logging:
  level:
    org.hibernate: WARN
    org.hibernate.orm.connections.pooling: ERROR

rsa:
  private-key: ${RSA_PRIVATE_KEY_PATH:certs/private.pem}
  public-key: ${RSA_PUBLIC_KEY_PATH:certs/public.pem}